"""
===============================================================================
UDUAK_QUANT_SYSTEM_PROJECT
-------------------------------------------------------------------------------
File: database/repositories/signal_repository.py

Description:
    Repository responsible for all database operations related to signals.

Responsibilities:
    - Insert signals
    - Retrieve signals
    - Update signal status
    - Delete signals
    - Query signal statistics

Business logic must NEVER exist here.
===============================================================================
"""

from __future__ import annotations

from typing import Any

from database.database import Database
from monitoring.logger import get_logger

logger = get_logger(__name__)


class SignalRepository:
    """
    Repository for signal database operations.
    """

    def __init__(self) -> None:
        """
        Initialize repository.
        """

        self._database = Database()

    # =========================================================================
    # CREATE
    # =========================================================================

    def insert_signal(
        self,
        *,
        symbol: str,
        strategy: str,
        timeframe: str,
        direction: str,
        entry_price: float,
        stop_loss: float,
        take_profit: float,
        confidence: float,
        status: str = "ACTIVE",
    ) -> int:
        """
        Insert a new signal.

        Returns
        -------
        int
            Database row ID.
        """

        cursor = self._database.execute(
            """
            INSERT INTO signals (

                symbol,
                strategy,
                timeframe,
                direction,
                entry_price,
                stop_loss,
                take_profit,
                confidence,
                status,
                created_at

            )
            VALUES (

                ?, ?, ?, ?, ?, ?, ?, ?, ?,
                CURRENT_TIMESTAMP

            )
            """,
            (
                symbol,
                strategy,
                timeframe,
                direction,
                entry_price,
                stop_loss,
                take_profit,
                confidence,
                status,
            ),
        )

        self._database.commit()

        logger.info(
            "Inserted signal for %s (%s)",
            symbol,
            strategy,
        )

        return cursor.lastrowid

    # =========================================================================
    # READ
    # =========================================================================

    def get_signal(
        self,
        signal_id: int,
    ) -> dict[str, Any] | None:
        """
        Retrieve a signal by ID.
        """

        cursor = self._database.execute(
            """
            SELECT *
            FROM signals
            WHERE id = ?
            """,
            (signal_id,),
        )

        row = cursor.fetchone()

        return dict(row) if row else None

    def get_all_signals(self) -> list[dict[str, Any]]:
        """
        Return all signals.
        """

        cursor = self._database.execute(
            """
            SELECT *
            FROM signals
            ORDER BY created_at DESC
            """
        )

        return [dict(row) for row in cursor.fetchall()]

    def get_active_signals(self) -> list[dict[str, Any]]:
        """
        Return active signals.
        """

        cursor = self._database.execute(
            """
            SELECT *
            FROM signals
            WHERE status='ACTIVE'
            ORDER BY created_at DESC
            """
        )

        return [dict(row) for row in cursor.fetchall()]

    def get_signals_by_symbol(
        self,
        symbol: str,
    ) -> list[dict[str, Any]]:
        """
        Return signals for a symbol.
        """

        cursor = self._database.execute(
            """
            SELECT *
            FROM signals
            WHERE symbol=?
            ORDER BY created_at DESC
            """,
            (symbol,),
        )

        return [dict(row) for row in cursor.fetchall()]

    def get_signals_by_strategy(
        self,
        strategy: str,
    ) -> list[dict[str, Any]]:
        """
        Return signals generated by a strategy.
        """

        cursor = self._database.execute(
            """
            SELECT *
            FROM signals
            WHERE strategy=?
            ORDER BY created_at DESC
            """,
            (strategy,),
        )

        return [dict(row) for row in cursor.fetchall()]

    # =========================================================================
    # UPDATE
    # =========================================================================

    def update_status(
        self,
        *,
        signal_id: int,
        status: str,
    ) -> bool:
        """
        Update signal status.
        """

        cursor = self._database.execute(
            """
            UPDATE signals
            SET status=?
            WHERE id=?
            """,
            (
                status,
                signal_id,
            ),
        )

        self._database.commit()

        updated = cursor.rowcount > 0

        if updated:
            logger.info(
                "Updated signal %s to %s",
                signal_id,
                status,
            )

        return updated

    def mark_executed(
        self,
        signal_id: int,
    ) -> bool:
        """
        Mark signal as executed.
        """

        return self.update_status(
            signal_id=signal_id,
            status="EXECUTED",
        )

    def mark_expired(
        self,
        signal_id: int,
    ) -> bool:
        """
        Mark signal as expired.
        """

        return self.update_status(
            signal_id=signal_id,
            status="EXPIRED",
        )

    def mark_cancelled(
        self,
        signal_id: int,
    ) -> bool:
        """
        Mark signal as cancelled.
        """

        return self.update_status(
            signal_id=signal_id,
            status="CANCELLED",
        )

    # =========================================================================
    # DELETE
    # =========================================================================

    def delete_signal(
        self,
        signal_id: int,
    ) -> bool:
        """
        Delete a signal.
        """

        cursor = self._database.execute(
            """
            DELETE
            FROM signals
            WHERE id=?
            """,
            (signal_id,),
        )

        self._database.commit()

        deleted = cursor.rowcount > 0

        if deleted:
            logger.warning(
                "Deleted signal %s",
                signal_id,
            )

        return deleted

    # =========================================================================
    # STATISTICS
    # =========================================================================

    def total_signals(self) -> int:
        """
        Return total signals.
        """

        cursor = self._database.execute(
            """
            SELECT COUNT(*)
            FROM signals
            """
        )

        return int(cursor.fetchone()[0])

    def active_signal_count(self) -> int:
        """
        Return number of active signals.
        """

        cursor = self._database.execute(
            """
            SELECT COUNT(*)
            FROM signals
            WHERE status='ACTIVE'
            """
        )

        return int(cursor.fetchone()[0])

    def executed_signal_count(self) -> int:
        """
        Return number of executed signals.
        """

        cursor = self._database.execute(
            """
            SELECT COUNT(*)
            FROM signals
            WHERE status='EXECUTED'
            """
        )

        return int(cursor.fetchone()[0])

    def expired_signal_count(self) -> int:
        """
        Return number of expired signals.
        """

        cursor = self._database.execute(
            """
            SELECT COUNT(*)
            FROM signals
            WHERE status='EXPIRED'
            """
        )

        return int(cursor.fetchone()[0])

    def cancelled_signal_count(self) -> int:
        """
        Return number of cancelled signals.
        """

        cursor = self._database.execute(
            """
            SELECT COUNT(*)
            FROM signals
            WHERE status='CANCELLED'
            """
        )

        return int(cursor.fetchone()[0])