"""

UDUAK_QUANT_SYSTEM_PROJECT

File: analysis/market_structure.py

Description:
    Determines market structure from swing highs and swing lows.

Responsibilities:
    - Validate swing data.
    - Identify Higher Highs (HH).
    - Identify Higher Lows (HL).
    - Identify Lower Highs (LH).
    - Identify Lower Lows (LL).
    - Prepare data for trend classification.

This module NEVER:
    - Reads MT5 data.
    - Retrieves candles.
    - Detects candle patterns.
    - Detects chart patterns.
    - Executes trades.
    - Performs risk management.

"""

from __future__ import annotations

from typing import List

from models.response import Response
from monitoring.logger import get_logger

logger = get_logger(__name__)

class MarketStructure:
    """
    Analyze market structure using swing highs and swing lows.

    This class receives swing points generated by SwingDetector
    and classifies the market structure.

    Future modules such as:

        - BOS
        - CHOCH
        - Liquidity
        - Order Blocks
        - Fair Value Gaps

    will use this module.
    """

    def __init__(
        self,
        lookback: int = 8,
    ) -> None:

        self.lookback = lookback

    # =====================================================================
    # PUBLIC METHODS
    # =====================================================================

    def analyze(
        self,
        swings: List[dict],
    ) -> Response:
        """
        Analyze market structure.

        Parameters

        swings : List[dict]
            Output from SwingDetector.

        Returns

        Response
            Standard project response.
        """

        # -------------------------------------------------------------
        # Validation
        # -------------------------------------------------------------

        if not swings:

            logger.error(
                "No swing data supplied."
            )

            return Response(
                success=False,
                message="No swing data supplied.",
                error="EMPTY_SWINGS",
                data=None,
            )

        if len(swings) < 2:

            logger.error(
                "At least two swings are required."
            )

            return Response(
                success=False,
                message=(
                    "At least two swings are required."
                ),
                error="INSUFFICIENT_SWINGS",
                data=None,
            )

        # -------------------------------------------------------------
        # Working copy
        # -------------------------------------------------------------

        structure = []

        previous_high = None

        previous_low = None

        trend = "UNKNOWN"

        # -------------------------------------------------------------
        # Build market structure
        # -------------------------------------------------------------

        for swing in swings:

            structure_item = {
                "type": swing["type"],
                "price": swing["price"],
                "time": swing["time"],
                "index": swing["index"],
                "structure": "",
            }

            # ---------------------------------------------------------
            # Swing High
            # ---------------------------------------------------------

            if swing["type"] == "SWING_HIGH":

                if previous_high is None:

                    structure_item["structure"] = (
                        "INITIAL_HIGH"
                    )

                elif swing["price"] > previous_high:

                    structure_item["structure"] = (
                        "HIGHER_HIGH"
                    )

                elif swing["price"] < previous_high:

                    structure_item["structure"] = (
                        "LOWER_HIGH"
                    )

                else:

                    structure_item["structure"] = (
                        "EQUAL_HIGH"
                    )

                previous_high = swing["price"]

            # ---------------------------------------------------------
            # Swing Low
            # ---------------------------------------------------------

            else:

                if previous_low is None:

                    structure_item["structure"] = (
                        "INITIAL_LOW"
                    )

                elif swing["price"] > previous_low:

                    structure_item["structure"] = (
                        "HIGHER_LOW"
                    )

                elif swing["price"] < previous_low:

                    structure_item["structure"] = (
                        "LOWER_LOW"
                    )

                else:

                    structure_item["structure"] = (
                        "EQUAL_LOW"
                    )

                previous_low = swing["price"]

            structure.append(
                structure_item
            )

        # -------------------------------------------------------------
        # Determine market trend from the most recent swings
        # -------------------------------------------------------------

        recent_structure = structure[-self.lookback:]

        structures = [
            item["structure"]
            for item in recent_structure
        ]

        higher_highs = structures.count(
            "HIGHER_HIGH"
        )

        higher_lows = structures.count(
            "HIGHER_LOW"
        )

        lower_highs = structures.count(
            "LOWER_HIGH"
        )

        lower_lows = structures.count(
            "LOWER_LOW"
        )

        equal_highs = structures.count(
            "EQUAL_HIGH"
        )

        equal_lows = structures.count(
            "EQUAL_LOW"
        )

        # -------------------------------------------------------------
        # Uptrend
        # -------------------------------------------------------------

        if (
            higher_highs >= 2
            and higher_lows >= 2
            and lower_lows == 0
        ):

            trend = "UPTREND"

        # -------------------------------------------------------------
        # Downtrend
        # -------------------------------------------------------------

        elif (
            lower_highs >= 2
            and lower_lows >= 2
            and higher_highs == 0
        ):

            trend = "DOWNTREND"

        # -------------------------------------------------------------
        # Transition
        # -------------------------------------------------------------

        elif (
            higher_highs > 0
            and lower_lows > 0
        ) or (
            lower_highs > 0
            and higher_lows > 0
        ):

            trend = "TRANSITION"

        # -------------------------------------------------------------
        # Range
        # -------------------------------------------------------------

        elif (
            equal_highs >= 2
            or equal_lows >= 2
        ):

            trend = "RANGE"

        else:

            trend = "UNKNOWN"

        # -------------------------------------------------------------
        # Log result
        # -------------------------------------------------------------

        logger.info(
            "Market structure analyzed successfully. "
            "Trend=%s | Swings=%d",
            trend,
            len(structure),
        )

        # -------------------------------------------------------------
        # Return response
        # -------------------------------------------------------------

        return Response(
            success=True,
            message=(
                "Market structure analyzed successfully."
            ),
            error=None,
            data={
                "trend": trend,
                "structure": structure,
                "statistics": {
                    "higher_highs": higher_highs,
                    "higher_lows": higher_lows,
                    "lower_highs": lower_highs,
                    "lower_lows": lower_lows,
                    "total_swings": len(structure),
                },
            },
        )